version: '3'
services:
  terraform:
    image: hashicorp/terraform
    container_name: 'terraform'
    entrypoint: ash
    tty: true
    
    volumes:
     - .:/terraform
    working_dir: /terraform
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-ap-northeast-1}

      