name: Terraform Apply

permissions:
  id-token: write
  contents: read

on:
    push:
  # workflow_run:
  #   workflows:
  #     - Terraform Validation
  #   branches:
  #     - main
  #   types:
  #     - completed

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.GITHUBACTIONS_OIDC_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Initialize Terraform
        working-directory: ./env/dev
        run: terraform init

      - name: Apply Terraform
        working-directory: ./env/dev
        run: terraform apply -auto-approve